import { Routes } from '@angular/router';
import { MaashreePage } from './pages/maashree-page/maashree-page';
import { LandingPage } from './pages/landing-page/landing-page';
import { ShreejaAshramComponent } from './pages/shreeja-ashram/shreeja-ashram.component';
import { DonatePageComponent } from './pages/donate-page/donate-page.component';
import { NewsletterJan2025Component } from './pages/newsletters/newsletter-jan-2025/newsletter-jan-2025';
import { NewslettersOverviewComponent } from './pages/newsletters/newsletters-overview/newsletters-overview';
import { NotFoundComponent } from './pages/not-found/not-found';
import { PrivacyPolicyComponent } from './pages/privacy-policy/privacy-policy';
import { StandForAnimalsComponent } from './pages/karmayog/stand-for-animals-page/stand-for-animals.component';
import { BhavasanaComponent } from './pages/karmayog/bhavasana-page/bhavasana.component';
import { ShreeGuruVidyalayaComponent } from './pages/karmayog/shree-guru-vidyalaya-page/shree-guru-vidyalaya.component';
import { IkshanaaComponent } from './pages/ikshanaa/ikshanaa.component';
import { WipComponent } from './pages/wip/wip.component';

export const routes: Routes = [
    { path: '', component: LandingPage },
    { path: 'maashree', component: MaashreePage },
    { path: 'shreeja-ashram', component: ShreejaAshramComponent },
    { path: 'donate', component: DonatePageComponent },
    { path: 'newsletters', component: NewslettersOverviewComponent },
    { path: 'newsletters/jan-2025', component: NewsletterJan2025Component },
    { path: 'karmayog/stand-for-animals', component: StandForAnimalsComponent },
    { path: 'karmayog/bhavasana', component: BhavasanaComponent },
    { path: 'karmayog/shree-guru-vidyalaya', component: ShreeGuruVidyalayaComponent },
    { path: 'ikshanaa', component: IkshanaaComponent },
    { path: 'privacy-policy', component: PrivacyPolicyComponent },
    { path: 'wip', component: WipComponent },
    { path: '404', component: NotFoundComponent },
    { path: '**', component: NotFoundComponent }
];
